"""empty message

Revision ID: 7fe7d7e5c79a
Revises: 
Create Date: 2021-10-23 13:13:06.570761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe7d7e5c79a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='交易id'),
    sa.Column('trade_address', sa.String(length=255), nullable=True, comment='交易地址'),
    sa.Column('client_address', sa.String(length=255), nullable=True, comment='用户地址'),
    sa.Column('amount', sa.Integer(), nullable=True, comment='数量'),
    sa.Column('item', sa.String(length=255), nullable=True, comment='项目'),
    sa.Column('is_use', sa.Boolean(), nullable=True, comment='是否有效'),
    sa.Column('is_transfer', sa.Boolean(), nullable=True, comment='是否转账'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_nft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True, comment='序号'),
    sa.Column('rare', sa.String(length=255), nullable=True, comment='稀有度'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名字'),
    sa.Column('discriblem', sa.String(length=255), nullable=False, comment='描述'),
    sa.Column('href', sa.String(length=255), nullable=True, comment='图片路径'),
    sa.Column('is_use', sa.Boolean(), nullable=True, comment='是否使用过'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True, comment='代币名'),
    sa.Column('symbol', sa.String(length=50), nullable=True, comment='代币符号'),
    sa.Column('precision', sa.Integer(), nullable=True, comment='小数点'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('hardtop', sa.Integer(), nullable=True, comment='总量'),
    sa.Column('ppt_url', sa.String(length=255), nullable=True, comment='路演ppt'),
    sa.Column('invest_img', sa.String(length=255), nullable=True, comment='投资方展示（图片路径）'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('login', sa.String(length=20), nullable=True, comment='用户名'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='哈希密码'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inital_digital_offering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True, comment='项目名'),
    sa.Column('token_id', sa.Integer(), nullable=True, comment='token主键'),
    sa.Column('logo', sa.String(length=255), nullable=True, comment='图标'),
    sa.Column('introduce', sa.String(length=255), nullable=True, comment='打新项目简介'),
    sa.Column('about', sa.String(length=255), nullable=True, comment='关于项目'),
    sa.Column('deadline', sa.DateTime(), nullable=True, comment='截止时间'),
    sa.Column('all_amount', sa.Integer(), nullable=True, comment='总数量'),
    sa.Column('current_amount', sa.Integer(), nullable=True, comment='当前认购数量'),
    sa.Column('people_all_amount', sa.Integer(), nullable=True, comment='总参与人数'),
    sa.Column('people_current_amount', sa.Integer(), nullable=True, comment='当前参与人数'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ico_id', sa.Integer(), nullable=True, comment='ico主键'),
    sa.Column('min', sa.Integer(), nullable=True, comment='最小认购额'),
    sa.Column('max', sa.Integer(), nullable=True, comment='最大认购额'),
    sa.Column('type', sa.String(length=20), nullable=True, comment='认购类型（public/private）'),
    sa.Column('market_value', sa.Integer(), nullable=True, comment='市值'),
    sa.Column('circulation', sa.Integer(), nullable=True, comment='开盘流通量'),
    sa.Column('subscribe', sa.Integer(), nullable=True, comment='总认购额'),
    sa.Column('unlock', sa.Text(), nullable=True, comment='解锁规则'),
    sa.Column('start_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['ico_id'], ['inital_digital_offering.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_pool')
    op.drop_table('inital_digital_offering')
    op.drop_table('user')
    op.drop_table('token')
    op.drop_table('photo_nft')
    op.drop_table('Trade')
    # ### end Alembic commands ###
